// Region 타입 정의.
export type Region = 'domestic' | 'overseas';

export const regions: Array<{ label: string; value: Region }> = [
  { label: '국내', value: 'domestic' },
  { label: '국외', value: 'overseas' },
];

export const subregions: Record<
  Region,
  Array<{ label: string; value: string }>
> = {
  domestic: [
    { label: '서울', value: 'seoul' },
    { label: '부산', value: 'busan' },
    { label: '대구', value: 'daegu' },
    { label: '인천', value: 'incheon' },
    { label: '광주', value: 'gwangju' },
    { label: '대전', value: 'daejeon' },
    { label: '울산', value: 'ulsan' },
    { label: '경기', value: 'gyeonggi' },
    { label: '강원', value: 'gangwon' },
    { label: '충북', value: 'chungbuk' },
    { label: '충남', value: 'chungnam' },
    { label: '전북', value: 'jeonbuk' },
    { label: '전남', value: 'jeonnam' },
    { label: '경북', value: 'gyeongbuk' },
    { label: '경남', value: 'gyeongnam' },
    { label: '제주', value: 'jeju' },
  ],
  overseas: [
    { label: '가나', value: 'ghana' },
    { label: '그리스', value: 'greece' },
    { label: '나이지리아', value: 'nigeria' },
    { label: '남아프리카공화국', value: 'south_africa' },
    { label: '네덜란드', value: 'netherlands' },
    { label: '노르웨이', value: 'norway' },
    { label: '뉴질랜드', value: 'new_zealand' },
    { label: '독일', value: 'germany' },
    { label: '러시아', value: 'russia' },
    { label: '말레이시아', value: 'malaysia' },
    { label: '멕시코', value: 'mexico' },
    { label: '모로코', value: 'morocco' },
    { label: '미국', value: 'usa' },
    { label: '베트남', value: 'vietnam' },
    { label: '브라질', value: 'brazil' },
    { label: '사우디아라비아', value: 'saudi_arabia' },
    { label: '스웨덴', value: 'sweden' },
    { label: '스위스', value: 'switzerland' },
    { label: '스페인', value: 'spain' },
    { label: '싱가포르', value: 'singapore' },
    { label: '아르헨티나', value: 'argentina' },
    { label: '아이슬란드', value: 'iceland' },
    { label: '아일랜드', value: 'ireland' },
    { label: '아프가니스탄', value: 'afghanistan' },
    { label: '영국', value: 'uk' },
    { label: '오스트리아', value: 'austria' },
    { label: '이집트', value: 'egypt' },
    { label: '이탈리아', value: 'italy' },
    { label: '인도', value: 'india' },
    { label: '인도네시아', value: 'indonesia' },
    { label: '일본', value: 'japan' },
    { label: '중국', value: 'china' },
    { label: '캐나다', value: 'canada' },
    { label: '케냐', value: 'kenya' },
    { label: '포르투갈', value: 'portugal' },
    { label: '폴란드', value: 'poland' },
    { label: '프랑스', value: 'france' },
    { label: '필리핀', value: 'philippines' },
    { label: '핀란드', value: 'finland' },
    { label: '터키', value: 'turkey' },
    { label: '태국', value: 'thailand' },
    { label: '호주', value: 'australia' },
  ],
};
